# Header

menu:
  最新: /
  所有文章: /archives/

# SubNav
subnav:
  github: "https://github.com/pilgrimerick"
  # weibo: "http://weibo.com/erick"
  # rss: /atom.xml
  #zhihu: "#"
  #douban: "#"
  #segmentfault: "#"
  mail: "mailto:erick1213@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: false

# 打赏
reward_type: 1
reward_wording: '如果文章对你有帮助，不妨小小打赏一下！'
alipay: https://cn.gravatar.com/userimage/109807169/4c06ac663fb5ed174811ef8d7f8fc07a.png?size=200
weixin: https://cn.gravatar.com/userimage/109807169/15f1efc943fabe7d4718d34d834ae1b6.png?size=200

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
baidu_analytics: false
google_analytics: false
favicon: /favicon.ico

#你的头像url
avatar: https://avatars1.githubusercontent.com/u/25657710?v=3&s=460

#是否开启分享
share_jia: false

mobile:
  social: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: 

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '搜索'
  friends: '友链'
  aboutme: '关于我'

friends:
  咖喱的博客: http://www.zogeli.com/
  落雨作品集: http://js-dev.cn/

aboutme: 姓名：林粤凯<br>年龄：23<br>简介：一枚一年在职前端，坐标深圳。<br>技术栈：Javascript / React / <br> Webpack / Gulp / Node.js